# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(580, 439)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.CMDInput = QtWidgets.QTextEdit(self.centralwidget)
        self.CMDInput.setGeometry(QtCore.QRect(120, 70, 151, 31))
        self.CMDInput.setObjectName("CMDInput")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(40, 30, 61, 21))
        self.label.setObjectName("label")
        self.SendCMD = QtWidgets.QPushButton(self.centralwidget)
        self.SendCMD.setGeometry(QtCore.QRect(280, 190, 75, 23))
        self.SendCMD.setObjectName("SendCMD")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(40, 200, 71, 21))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(370, 60, 131, 16))
        self.label_3.setObjectName("label_3")
        self.ACKDisplay = QtWidgets.QTextBrowser(self.centralwidget)
        self.ACKDisplay.setGeometry(QtCore.QRect(360, 90, 151, 111))
        self.ACKDisplay.setObjectName("ACKDisplay")
        self.CRCDisplay = QtWidgets.QTextBrowser(self.centralwidget)
        self.CRCDisplay.setGeometry(QtCore.QRect(120, 190, 151, 31))
        self.CRCDisplay.setObjectName("CRCDisplay")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(40, 250, 61, 21))
        self.label_4.setObjectName("label_4")
        self.CMDLabelDisplay = QtWidgets.QTextBrowser(self.centralwidget)
        self.CMDLabelDisplay.setGeometry(QtCore.QRect(120, 240, 151, 31))
        self.CMDLabelDisplay.setObjectName("CMDLabelDisplay")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(40, 320, 51, 31))
        self.label_5.setObjectName("label_5")
        self.CMDBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.CMDBrowser.setGeometry(QtCore.QRect(120, 300, 151, 71))
        self.CMDBrowser.setObjectName("CMDBrowser")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(40, 130, 61, 21))
        self.label_6.setObjectName("label_6")
        self.PortName = QtWidgets.QLineEdit(self.centralwidget)
        self.PortName.setGeometry(QtCore.QRect(200, 130, 71, 20))
        self.PortName.setObjectName("PortName")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(120, 30, 81, 21))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(40, 80, 61, 21))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(380, 220, 111, 16))
        self.label_8.setObjectName("label_8")
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(360, 250, 151, 121))
        self.textBrowser.setObjectName("textBrowser")
        self.comboBox_2 = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_2.setGeometry(QtCore.QRect(120, 130, 71, 22))
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 580, 26))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menumesh = QtWidgets.QMenu(self.menubar)
        self.menumesh.setObjectName("menumesh")
        MainWindow.setMenuBar(self.menubar)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menumesh.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "指令类型"))
        self.SendCMD.setText(_translate("MainWindow", "发送指令"))
        self.label_2.setText(_translate("MainWindow", "CRC校验码"))
        self.label_3.setText(_translate("MainWindow", "下位机信息比特流"))
        self.label_4.setText(_translate("MainWindow", "指令标签"))
        self.label_5.setText(_translate("MainWindow", "指令流"))
        self.label_6.setText(_translate("MainWindow", "串口设备名"))
        self.comboBox.setItemText(0, _translate("MainWindow", "时间同步"))
        self.comboBox.setItemText(1, _translate("MainWindow", "传感信息"))
        self.comboBox.setItemText(2, _translate("MainWindow", "节点控制"))
        self.comboBox.setItemText(3, _translate("MainWindow", "路由信息"))
        self.comboBox.setItemText(4, _translate("MainWindow", "设备状态"))
        self.comboBox.setItemText(5, _translate("MainWindow", "网络变更"))
        self.label_7.setText(_translate("MainWindow", "指令内容"))
        self.label_8.setText(_translate("MainWindow", "下位机信息解码"))
        self.comboBox_2.setItemText(0, _translate("MainWindow", "COM"))
        self.comboBox_2.setItemText(1, _translate("MainWindow", "/dev/tty"))
        self.menu.setTitle(_translate("MainWindow", "上位机模拟"))
        self.menumesh.setTitle(_translate("MainWindow", "mesh信息模拟"))

